version: '3.9'
services:
  app:
    build: .
    ports:
      - "3000:3000"
    depends_on:
      - postgres
      - redis
      - rabbitmq
    environment:
      DATABASE_HOST: postgres
      REDIS_HOST: redis
      RABBITMQ_URL: amqp://rabbitmq

  postgres:
    image: postgres:13
    container_name: postgres
    environment:
      POSTGRES_USER: your_postgres_user
      POSTGRES_PASSWORD: your_postgres_password
      POSTGRES_DB: nestjs_test
    ports:
      - "5432:5432"

  redis:
    image: redis:6
    container_name: redis
    ports:
      - "6379:6379"

  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
